### ISSUE TITLE
Tags are ignored when provided with a search query

### ISSUE THREAD

**Issue by mattco98** [ChatTriggers/website-backend#7]
When sending a `GET /modules` request, if both the `tags` and the `q` parameter are specified, the `tags` are completely ignored. The correct behavior would be only applying the search to modules that have all of the provided `tags`.

**Comment by FalseHonesty** [comment]
I cannot seem to reproduce this issue when sending manual API requests.

When sending the request `GET http://localhost:7000/api/modules?q=the` I get this response https://hasteb.in/mevodena.json.

When sending the request `GET http://localhost:7000/api/modules?q=the&tags=HUD` I get this response https://hasteb.in/ubewehuc.json.

As far as I can tell this is the intended behaviour, but I might be missing something.

**Comment by mattco98** [comment]
Seeing the same thing here. I'll reopen if any weird behavior emerges. I have yet to _really_ add tag searching, and there aren't that many modules with tags anyways.
